# Generated by Django 3.2.8 on 2021-10-26 06:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20211020_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemList',
            new_name='UserItem',
        ),
    ]
