# Generated by Django 3.2.9 on 2021-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211106_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='inner_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
